import * as rx from 'rxjs';
import { loadConfig } from './config.js';
import { startRelayerWallet } from './wallet.js';

/**
 * Registers the relayer's NIGHT UTXOs for passive DUST generation.
 *
 *     npm run relayer:dust
 *
 * NIGHT alone cannot pay a fee. DUST is what pays, and DUST is generated by
 * NIGHT that has been registered for it. A relayer holding NIGHT but not
 * registered will fail every vote at the fee step, which is the failure this
 * script exists to prevent.
 *
 * Only the owner of the UTXOs can register them — the signature comes from the
 * relayer's own unshielded keystore — so no other wallet can do this on its
 * behalf. The registration transaction is finalized and submitted without a
 * balancing step, which is what breaks the chicken-and-egg of needing DUST in
 * order to obtain DUST.
 */
const config = loadConfig();
console.log(`network: ${config.networkId}`);
console.log('starting relayer wallet and syncing (this can take several minutes)…');

const wallet = await startRelayerWallet(config);

/** Minutes to wait for the funding UTXO to appear before giving up. */
const WAIT_FOR_NIGHT_MS = 8 * 60 * 1000;

try {
  // What this step actually needs is the NIGHT UTXOs, not a fully synced
  // chain. Waiting on waitForSyncedState() blocks in silence for far longer
  // than necessary and looks like a hang. Wait for the real precondition, and
  // narrate progress so the terminal is never dead.
  let latest: Awaited<ReturnType<typeof wallet.facade.waitForSyncedState>> | null = null;
  let lastLog = 0;

  const state = await rx
    .firstValueFrom(
      wallet.facade.state().pipe(
        rx.tap((s) => {
          latest = s;
          const now = Date.now();
          if (now - lastLog > 10_000) {
            lastLog = now;
            console.log(
              `  syncing… synced=${s.isSynced} night=${s.unshielded.availableCoins.length} dust=${s.dust.availableCoins.length}`,
            );
          }
        }),
        rx.filter((s) => s.unshielded.availableCoins.length > 0),
        rx.timeout({ first: WAIT_FOR_NIGHT_MS, each: WAIT_FOR_NIGHT_MS }),
      ),
    )
    .catch(() => latest);

  if (!state) {
    console.error('\nThe wallet produced no state at all. Check the indexer URL in relayer/.env.');
    process.exit(1);
  }

  const nightCoins = state.unshielded.availableCoins;
  const alreadyRegistered = nightCoins.filter((coin) => coin.meta.registeredForDustGeneration);
  const unregistered = nightCoins.filter((coin) => !coin.meta.registeredForDustGeneration);

  console.log(`NIGHT UTXOs: ${nightCoins.length} (registered: ${alreadyRegistered.length})`);
  console.log(`current DUST: ${state.dust.balance(new Date()).toString()}`);

  if (nightCoins.length === 0) {
    console.error(
      '\nThis wallet holds no NIGHT. Fund the unshielded address printed by\n' +
        '`npm run relayer:address` first, wait for it to confirm, then rerun.',
    );
    process.exitCode = 1;
  } else if (unregistered.length === 0) {
    console.log('\nEvery NIGHT UTXO is already registered. Nothing to do.');
  } else {
    const estimate = await wallet.facade.estimateRegistration(unregistered);
    console.log(`registration fee estimate: ${estimate.fee.toString()}`);
    console.log(`registering ${unregistered.length} UTXO(s)…`);

    const recipe = await wallet.facade.registerNightUtxosForDustGeneration(
      unregistered,
      wallet.unshieldedKeystore.getPublicKey(),
      (payload) => wallet.unshieldedKeystore.signData(payload),
    );
    const finalized = await wallet.facade.finalizeRecipe(recipe);
    const txId = await wallet.facade.submitTransaction(finalized);
    console.log(`submitted: ${txId}`);

    console.log('waiting for DUST to appear…');
    const after = await rx.firstValueFrom(
      wallet.facade.state().pipe(
        rx.filter((s) => s.isSynced),
        rx.filter((s) => s.dust.availableCoins.length > 0),
      ),
    );
    console.log(`\nDUST coins: ${after.dust.availableCoins.length}`);
    console.log(`DUST balance: ${after.dust.balance(new Date()).toString()}`);
    console.log('\nThe relayer can now pay for votes.');
  }
} finally {
  await wallet.stop().catch(() => undefined);
}
process.exit(0);
