import type { CicoLocale } from '@/integration/locale';

const en = {
  welcome: 'Your voice.\nYour choice.',
  secret: 'Your secret.',
  invitation: 'A little privacy. A new way to take part.',
  start: 'Get started',
  returning: 'Already have Passport? Connect',
  privacyTitle: 'A voice of your own.\nPrivacy by design.',
  privacyBody:
    'Midnight uses mathematics to prove something about you without revealing the private details behind it. This is selective disclosure.',
  private: 'Your personal details',
  privateNote: 'Stay private',
  shared: 'Only what is needed',
  sharedNote: 'For example: over 18',
  features: ['Explore civic consultations', 'Share your perspective privately'],
  more: 'How does it work?',
  detail:
    'A proof can confirm that you meet a requirement without sharing the underlying document. The document-reading step processes the page on your device; any provider handoff is explained before you continue.',
  connectTitle: 'Meet your\nMidnight Passport.',
  connectBody: 'Your secure way to sign in. You choose which profile details to share.',
  connect: 'Connect Midnight Passport',
  demo: 'Use demo Passport',
  skip: 'Skip for now',
  later: 'Do this later',
  shares: 'Shares your approved profile',
  protects: 'Your document and voting choices stay separate',
  waiting: 'Waiting for Passport…',
  cancel: 'Cancel connection',
  connected: 'Passport connected',
  continue: 'Continue',
  error: 'We couldn’t connect to Passport. Please try again.',
  documentTitle: 'Your passport.\nJust the essentials.',
  documentBody:
    'Your physical passport can help prove eligibility, such as your country and whether you are over 18. It is separate from your Midnight Passport account.',
  documentNote: 'You can explore first and verify when you are ready.',
  verify: 'Verify my passport',
  demoTitle: 'Try with a simulated pass',
  demoNote: 'Demo only · no document or real proof needed.',
  country: 'Choose a test country',
  create: 'Create my simulated pass',
  success: 'Your simulated pass is ready.',
  successBody: 'Explore the consultations and try a test vote.',
  dashboard: 'See the consultations',
  simulated: 'Simulated pass',
  testCountry: 'Test country',
  age: 'Age class',
  back: 'Previous step',
  exit: 'Back to the app',
  language: 'Language',
  step: 'Step',
  of: 'of',
};
type Copy = { [K in keyof typeof en]: (typeof en)[K] };
export const ONBOARDING_COPY: Record<CicoLocale, Copy> = {
  en,
  es: {
    welcome: 'Tu voz.\nTu elección.',
    secret: 'Tu secreto.',
    invitation: 'Un poco de privacidad. Otra forma de participar.',
    start: 'Comenzar',
    returning: '¿Ya tenés Passport? Conectate',
    privacyTitle: 'Tu propia voz.\nPrivacidad desde el inicio.',
    privacyBody:
      'Midnight usa las matemáticas para demostrar algo sobre vos sin revelar los datos privados que lo respaldan. Esto es divulgación selectiva.',
    private: 'Tus datos personales',
    privateNote: 'Se mantienen privados',
    shared: 'Solo lo necesario',
    sharedNote: 'Por ejemplo: mayor de 18',
    features: ['Explorá consultas ciudadanas', 'Compartí tu perspectiva en privado'],
    more: '¿Cómo funciona?',
    detail:
      'Una prueba puede confirmar que cumplís un requisito sin compartir el documento. La lectura de la página se procesa en tu dispositivo; cualquier paso hacia un proveedor se explica antes de continuar.',
    connectTitle: 'Conocé tu\nMidnight Passport.',
    connectBody: 'Tu forma segura de ingresar. Vos elegís qué datos de perfil compartir.',
    connect: 'Conectar Midnight Passport',
    demo: 'Usar Passport de demo',
    skip: 'Omitir por ahora',
    later: 'Hacerlo más tarde',
    shares: 'Comparte el perfil que aprobás',
    protects: 'Tu documento y tus votos se mantienen separados',
    waiting: 'Esperando a Passport…',
    cancel: 'Cancelar conexión',
    connected: 'Passport conectado',
    continue: 'Continuar',
    error: 'No pudimos conectar Passport. Intentá otra vez.',
    documentTitle: 'Tu pasaporte.\nSolo lo esencial.',
    documentBody:
      'Tu pasaporte físico puede demostrar elegibilidad, como tu país y si sos mayor de 18. Es distinto de tu cuenta Midnight Passport.',
    documentNote: 'Podés explorar primero y verificar cuando estés listo.',
    verify: 'Verificar mi pasaporte',
    demoTitle: 'Probar con un pase simulado',
    demoNote: 'Solo demo · sin documento ni prueba real.',
    country: 'Elegí un país de prueba',
    create: 'Crear mi pase simulado',
    success: 'Tu pase simulado está listo.',
    successBody: 'Explorá las consultas y probá un voto de prueba.',
    dashboard: 'Ver las consultas',
    simulated: 'Pase simulado',
    testCountry: 'País de prueba',
    age: 'Clase de edad',
    back: 'Paso anterior',
    exit: 'Volver a la app',
    language: 'Idioma',
    step: 'Paso',
    of: 'de',
  },
  fr: {
    welcome: 'Votre voix.\nVotre choix.',
    secret: 'Votre secret.',
    invitation: 'Un peu de confidentialité. Une autre façon de participer.',
    start: 'Commencer',
    returning: 'Déjà un Passport ? Connectez-vous',
    privacyTitle: 'Votre propre voix.\nLa confidentialité par nature.',
    privacyBody:
      'Midnight utilise les mathématiques pour prouver quelque chose à votre sujet sans révéler les détails privés qui le justifient. C’est la divulgation sélective.',
    private: 'Vos données personnelles',
    privateNote: 'Restent privées',
    shared: 'Seulement le nécessaire',
    sharedNote: 'Par exemple : plus de 18 ans',
    features: ['Explorez les consultations citoyennes', 'Partagez votre point de vue en privé'],
    more: 'Comment ça fonctionne ?',
    detail:
      'Une preuve peut confirmer que vous remplissez une condition sans partager le document. La lecture de la page est traitée sur votre appareil ; tout transfert vers un prestataire est expliqué avant de continuer.',
    connectTitle: 'Découvrez votre\nMidnight Passport.',
    connectBody:
      'Votre connexion sécurisée. Vous choisissez les informations de profil à partager.',
    connect: 'Connecter Midnight Passport',
    demo: 'Utiliser le Passport de démo',
    skip: 'Passer pour le moment',
    later: 'Le faire plus tard',
    shares: 'Partage votre profil approuvé',
    protects: 'Votre document et vos votes restent séparés',
    waiting: 'En attente de Passport…',
    cancel: 'Annuler la connexion',
    connected: 'Passport connecté',
    continue: 'Continuer',
    error: 'Impossible de connecter Passport. Réessayez.',
    documentTitle: 'Votre passeport.\nJuste l’essentiel.',
    documentBody:
      'Votre passeport physique peut prouver votre éligibilité, comme votre pays et votre majorité. Il est distinct de votre compte Midnight Passport.',
    documentNote: 'Explorez d’abord et vérifiez quand vous le souhaitez.',
    verify: 'Vérifier mon passeport',
    demoTitle: 'Essayer un laissez-passer simulé',
    demoNote: 'Démo uniquement · sans document ni preuve réelle.',
    country: 'Choisissez un pays de test',
    create: 'Créer mon laissez-passer simulé',
    success: 'Votre laissez-passer simulé est prêt.',
    successBody: 'Explorez les consultations et essayez un vote de test.',
    dashboard: 'Voir les consultations',
    simulated: 'Laissez-passer simulé',
    testCountry: 'Pays de test',
    age: 'Classe d’âge',
    back: 'Étape précédente',
    exit: 'Retour à l’application',
    language: 'Langue',
    step: 'Étape',
    of: 'sur',
  },
};
