export const PULSE_COPY = {
  en: {
    name: 'Civic pulse',
    private: 'Private reflection',
    back: 'Back',
    exit: 'Back to the app',
    next: 'Continue',
    start: 'Start reflecting',
    begin: 'Begin',
    skip: 'Skip',
    review: 'Review',
    finish: 'Finish reflection',
    edit: 'Edit',
    erase: 'Erase answers and return home',
    optional: 'Optional',
    required: 'Choose one to three',
    step: 'Step',
    of: 'of',
    selected: 'selected',
    skipped: 'Skipped',
    cap: 'Choose up to three priorities. Remove one before adding another.',
    homeTitle: 'Start with what\nmatters to you.',
    homeBody:
      'Before considering a proposal, take a moment to notice the changes you would like to see around you.',
    duration: '3 questions · About 2 minutes',
    homeNote: 'A reflection, not a vote. No account needed.',
    introTitle: 'There is room\nfor your perspective.',
    introBody:
      'Think about your everyday life and the people around you. There is no right answer, score, or political label.',
    privacy:
      'Your answers stay in this open page. Nothing is sent or saved. You can skip optional questions or erase everything.',
    titles: [
      'Where would meaningful change make the biggest difference?',
      'When priorities compete, what should guide a decision?',
      'What would help you make a more informed choice?',
      'Take a moment to look back.',
    ],
    bodies: [
      'Think about daily life in your community. Choose up to three areas that deserve more attention.',
      'Choose the approaches you value. They can coexist; different situations may call for different choices.',
      'Choose the information you would want before forming a view on a proposal.',
      'Does this reflect what matters to you today? You can change any answer.',
    ],
    groups: ['Priorities', 'Values and tradeoffs', 'Information you need'],
    priorities: [
      ['Cost of living', 'Everyday prices and household security'],
      ['Healthcare', 'Timely physical and mental healthcare'],
      ['Education', 'Learning and opportunity throughout life'],
      ['Housing', 'Safe, stable places to live'],
      ['Climate resilience', 'Communities ready for a changing climate'],
      ['Public safety', 'Prevention, support and trusted justice'],
    ],
    values: [
      ['Act sooner', 'Try a practical first step and learn from the results.'],
      ['Build consensus', 'Listen broadly before committing to a lasting change.'],
      ['Target support', 'Focus resources where the need is greatest.'],
      ['Universal services', 'Make essential support easy for everyone to access.'],
      ['Prefer not to answer', 'I would rather consider a specific proposal first.'],
    ],
    information: [
      'Costs and funding',
      'How delivery would work',
      'Evidence for likely outcomes',
      'Who benefits and what is traded off',
    ],
    completeTitle: 'A little more clarity.',
    completeBody:
      'You have made space for your priorities and questions. Keep that perspective as you explore the consultations.',
    completeNote:
      'No answer was submitted or saved. This is your reflection, not an assessment of your beliefs.',
  },
  es: {
    name: 'Pulso cívico',
    private: 'Reflexión privada',
    back: 'Atrás',
    exit: 'Volver a la app',
    next: 'Continuar',
    start: 'Empezar a reflexionar',
    begin: 'Comenzar',
    skip: 'Omitir',
    review: 'Revisar',
    finish: 'Terminar la reflexión',
    edit: 'Editar',
    erase: 'Borrar respuestas y volver',
    optional: 'Opcional',
    required: 'Elegí de una a tres',
    step: 'Paso',
    of: 'de',
    selected: 'seleccionadas',
    skipped: 'Omitido',
    cap: 'Elegí hasta tres prioridades. Quitá una antes de añadir otra.',
    homeTitle: 'Empezá por lo\nque te importa.',
    homeBody:
      'Antes de considerar una propuesta, tomáte un momento para pensar qué cambios te gustaría ver a tu alrededor.',
    duration: '3 preguntas · Unos 2 minutos',
    homeNote: 'Una reflexión, no un voto. No necesitás una cuenta.',
    introTitle: 'Hay espacio para\ntu perspectiva.',
    introBody:
      'Pensá en tu vida cotidiana y en quienes te rodean. No hay respuestas correctas, puntajes ni etiquetas políticas.',
    privacy:
      'Tus respuestas quedan en esta página abierta. Nada se envía ni se guarda. Podés omitir preguntas opcionales o borrar todo.',
    titles: [
      '¿Dónde podría un cambio mejorar más la vida cotidiana?',
      'Cuando las prioridades compiten, ¿qué debería orientar una decisión?',
      '¿Qué te ayudaría a tomar una decisión más informada?',
      'Tomáte un momento para mirar atrás.',
    ],
    bodies: [
      'Pensá en tu comunidad. Elegí hasta tres áreas que merecen más atención.',
      'Elegí los enfoques que valorás. Pueden convivir; distintas situaciones requieren distintas decisiones.',
      'Elegí la información que querrías conocer antes de formarte una opinión.',
      '¿Esto refleja lo que te importa hoy? Podés cambiar cualquier respuesta.',
    ],
    groups: ['Prioridades', 'Valores y decisiones', 'Información que necesitás'],
    priorities: [
      ['Costo de vida', 'Precios cotidianos y seguridad económica'],
      ['Salud', 'Atención física y mental a tiempo'],
      ['Educación', 'Aprendizaje y oportunidades durante toda la vida'],
      ['Vivienda', 'Lugares seguros y estables donde vivir'],
      ['Resiliencia climática', 'Comunidades preparadas para el cambio climático'],
      ['Seguridad pública', 'Prevención, apoyo y justicia confiable'],
    ],
    values: [
      ['Actuar antes', 'Dar un primer paso práctico y aprender del resultado.'],
      ['Construir consenso', 'Escuchar distintas voces antes de un cambio duradero.'],
      ['Focalizar el apoyo', 'Priorizar a quienes más lo necesitan.'],
      ['Servicios universales', 'Facilitar el acceso de todos a los servicios esenciales.'],
      ['Prefiero no responder', 'Preferiría considerar primero una propuesta concreta.'],
    ],
    information: [
      'Costos y financiación',
      'Cómo se implementaría',
      'Evidencia sobre los resultados',
      'Quién se beneficia y qué se sacrifica',
    ],
    completeTitle: 'Un poco más de claridad.',
    completeBody:
      'Le diste espacio a tus prioridades y preguntas. Llevá esa perspectiva a las consultas que explores.',
    completeNote:
      'No se envió ni se guardó ninguna respuesta. Es tu reflexión, no una evaluación de tus creencias.',
  },
  fr: {
    name: 'Pouls civique',
    private: 'Réflexion privée',
    back: 'Retour',
    exit: 'Retour à l’application',
    next: 'Continuer',
    start: 'Commencer à réfléchir',
    begin: 'Commencer',
    skip: 'Passer',
    review: 'Revoir',
    finish: 'Terminer la réflexion',
    edit: 'Modifier',
    erase: 'Effacer les réponses et revenir',
    optional: 'Facultatif',
    required: 'Choisissez de un à trois',
    step: 'Étape',
    of: 'sur',
    selected: 'sélectionnés',
    skipped: 'Passé',
    cap: 'Choisissez trois priorités au maximum. Retirez-en une pour en ajouter une autre.',
    homeTitle: 'Commencez par\nce qui compte.',
    homeBody:
      'Avant de considérer une proposition, prenez un moment pour imaginer les changements que vous aimeriez voir autour de vous.',
    duration: '3 questions · Environ 2 minutes',
    homeNote: 'Une réflexion, pas un vote. Aucun compte nécessaire.',
    introTitle: 'Votre perspective\na toute sa place.',
    introBody:
      'Pensez à votre quotidien et aux personnes autour de vous. Il n’y a ni bonne réponse, ni score, ni étiquette politique.',
    privacy:
      'Vos réponses restent dans cette page ouverte. Rien n’est envoyé ni enregistré. Vous pouvez passer les questions facultatives ou tout effacer.',
    titles: [
      'Où un changement améliorerait-il le plus le quotidien ?',
      'Quand les priorités se confrontent, que faut-il privilégier ?',
      'Qu’est-ce qui vous aiderait à faire un choix plus éclairé ?',
      'Prenez un instant pour faire le point.',
    ],
    bodies: [
      'Pensez à votre communauté. Choisissez jusqu’à trois domaines qui méritent davantage d’attention.',
      'Choisissez les approches qui comptent pour vous. Elles peuvent coexister selon la situation.',
      'Choisissez les informations que vous voudriez connaître avant de vous faire une opinion.',
      'Cela reflète-t-il vos priorités aujourd’hui ? Vous pouvez modifier chaque réponse.',
    ],
    groups: ['Priorités', 'Valeurs et arbitrages', 'Informations nécessaires'],
    priorities: [
      ['Coût de la vie', 'Prix du quotidien et sécurité financière'],
      ['Santé', 'Des soins physiques et psychiques à temps'],
      ['Éducation', 'Apprentissage et possibilités tout au long de la vie'],
      ['Logement', 'Des lieux sûrs et stables où vivre'],
      ['Résilience climatique', 'Des communautés prêtes au changement climatique'],
      ['Sécurité publique', 'Prévention, soutien et justice de confiance'],
    ],
    values: [
      ['Agir plus tôt', 'Faire un premier pas concret et apprendre du résultat.'],
      ['Construire un consensus', 'Écouter largement avant un changement durable.'],
      ['Cibler le soutien', 'Concentrer les ressources là où les besoins sont les plus grands.'],
      ['Services universels', 'Rendre les services essentiels accessibles à tous.'],
      ['Je préfère ne pas répondre', 'Je préfère considérer une proposition précise.'],
    ],
    information: [
      'Coûts et financement',
      'Mise en œuvre concrète',
      'Preuves des résultats attendus',
      'Bénéficiaires et compromis',
    ],
    completeTitle: 'Un peu plus de clarté.',
    completeBody:
      'Vous avez pris le temps de réfléchir à vos priorités et questions. Gardez cette perspective en explorant les consultations.',
    completeNote:
      'Aucune réponse n’a été envoyée ni enregistrée. C’est votre réflexion, pas une évaluation de vos convictions.',
  },
} as const;
