export const CHAT_PROMPTS = {
  en: {
    thinking: 'Finding catalogue context',
    places: 'Places',
    topics: 'Topics',
    follow: 'Explore this proposal',
    arguments: 'Arguments',
    evidence: 'Context',
    uncertainty: 'What is uncertain?',
    sources: 'Sources',
    topicNames: ['Climate', 'Economy', 'Housing', 'Mobility'],
    prompt: 'Show open consultations about',
    stop: 'Show answer now',
  },
  es: {
    thinking: 'Buscando contexto del catálogo',
    places: 'Lugares',
    topics: 'Temas',
    follow: 'Explorá esta propuesta',
    arguments: 'Argumentos',
    evidence: 'Contexto',
    uncertainty: '¿Qué incertidumbres hay?',
    sources: 'Fuentes',
    topicNames: ['Clima', 'Economía', 'Vivienda', 'Movilidad'],
    prompt: 'Mostrar consultas abiertas sobre',
    stop: 'Ver respuesta ahora',
  },
  fr: {
    thinking: 'Recherche du contexte du catalogue',
    places: 'Lieux',
    topics: 'Thèmes',
    follow: 'Explorer cette proposition',
    arguments: 'Arguments',
    evidence: 'Contexte',
    uncertainty: 'Quelles incertitudes ?',
    sources: 'Sources',
    topicNames: ['Climat', 'Économie', 'Logement', 'Mobilité'],
    prompt: 'Afficher les consultations ouvertes sur',
    stop: 'Voir la réponse',
  },
} as const;
